name: dist-s1-val
channels:
  - conda-forge
dependencies:
  - python>=3.11 # required for shapely 2.0.0
  - pip
  # For packaging, and testing
  - dem_stitcher
  - rasterio
  - dist-s1
  - numpy
  - matplotlib
  - geopandas
  - shapely
  - pandas
  - tqdm
  - ruff
  - jupyterlab
  - jupyter